# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Reached' do
pod 'TextFieldEffects'
pod 'OneSignal'
pod 'Mixpanel'
end

target 'ReachedTests' do

end

target 'ReachedUITests' do

end

